### ISSUE TITLE
expose volZ 

### ISSUE THREAD

**Issue by alisterburt** [EuanPyle/lil_aretomo#2]
the volZ parameter in AreTomo is pretty useful

we could maybe expose it as `expected_sample_thickness` in angstroms/nanometers, what do you think?

edit: to be clear, we would take in `expected_sample_thickness` and calculate the value to be passed to volZ, maybe as 1.5x expected sample thickness or something (in px)

**Comment by EuanPyle** [comment]
Funnily enough, this was on my to do list today after someone had been telling me how useful the AlignZ option was! Will tell you when it's up on PyPi (along with the other issues)

**Comment by EuanPyle** [comment]
By default, I have set volZ to 0 so it generates an aligned TS rather than a tomogram - if I set VolZ to a value AreTomo will generate a tomogram which I think it's better not to and instead use rln's generate tomogram function. Think its probably best to use tomos generated by rln so there's no chance of picked coordinates differing.

But AlignZ is definitely is useful as this aligns between certain thickness and ignores blank space and I'm going to integrate that now!

**Comment by EuanPyle** [comment]
Ready to upload to PyPi (addition of AlignZ and changes from other issue), lmk if you're ok with that!

**Comment by alisterburt** [comment]
Ooh okay I think I meant AlignZ, thanks for clarifying!

Could you check that the xf file produced when VolZ = 0 isn't empty? I seem to remember it zeroing them because all transforms are already applied on the aligned ts - we want the transforms that align the ts as input to relion

I agree that generating a tomogram is less than ideal - maybe we clean that up as part of the 'align single tilt' series utility over in the preprocessing package :)

Sorry for not checking some of this stuff myself, still travelling!
